####################################################################
# Dune module information file: This file gets parsed by dunecontrol
# and by the CMake build scripts.
####################################################################

Module: opm-core
Description: Open Porous Media Initiative Core Library
Version: 2018.04-pre
Label: 2018.04-pre
Maintainer: atgeirr@sintef.no
MaintainerName: Atgeirr F. Rasmussen
Url: http://opm-project.org
Depends: dune-common (>= 2.4) dune-istl (>= 2.4) opm-common opm-parser opm-grid opm-output opm-material
